version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: packages/py-genomics-utils/docs/conf.py

python:
  install:
    - requirements: packages/py-genomics-utils/docs/requirements.txt
    - method: pip
      path: packages/py-genomics-utils
